let a=[{    name:"ragu",
    phone:11111111,
    email:"ragu@gmail.com",
    address:"tirupur"
},
{
    name:"cheran",
    phone:22222222,
    email:"cheran@gmail.com",
    address:"bangalore"
},
{
    name:"indhu",
    phone:33333333,
    email:"indhu@gmail.com",
    address:"chennai"
},
{
    name:"raj",
    phone:44444444,
    email:"raj@gmail.com",
    address:"tirupur"
},
{
    name:"ram",
    phone:55555555,
    email:"ram@gmail.com",
    address:"bangalore"
},
{
    name:"abi",
    phone:66666666,
    email:"abi@gmail.com",
    address:"chennai"
},
{
    name:"iniya",
    phone:77777777,
    email:"iniya@gmail.com",
    address:"tirupur"
},
{
    name:"vel",
    phone:8888888,
    email:"vel@gmail.com",
    address:"bangalore"
},
{
    name:"ramya",
    phone:99999999,
    email:"ramya@gmail.com",
    address:"chennai"
}

]
b="tirupur"
for(let i of a){
    if(i.address==b){
    console.log(i)
}
}